version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/microblog_db
      - SECRET_KEY=dev-secret-key

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microblog_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
